name: Deploy HanaBank Backend to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-hanabank-backend-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: hanabank-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Deploy to EC2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "export ORACLE_DB_URL='${{ secrets.ORACLE_DB_URL }}' && \
             export ORACLE_DB_USERNAME='${{ secrets.ORACLE_DB_USERNAME }}' && \
             export ORACLE_DB_PASSWORD='${{ secrets.ORACLE_DB_PASSWORD }}' && \
             bash -s" << 'EOF'
            echo "IAM 역할과 ECR Credential Helper 사용으로 자동 인증"
            
            docker stop hanabank-backend || true
            docker rm -f hanabank-backend || true
            
            docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            
            echo " 환경변수 확인:"
            echo "ORACLE_DB_URL 길이: ${#ORACLE_DB_URL}"
            echo "ORACLE_DB_USERNAME 길이: ${#ORACLE_DB_USERNAME}"
            echo "ORACLE_DB_PASSWORD 길이: ${#ORACLE_DB_PASSWORD}"
            
            echo " GitHub Secrets 상태 확인:"
            echo "ORACLE_DB_URL 설정 여부: ${{ secrets.ORACLE_DB_URL != '' }}"
            echo "ORACLE_DB_USERNAME 설정 여부: ${{ secrets.ORACLE_DB_USERNAME != '' }}"
            echo "ORACLE_DB_PASSWORD 설정 여부: ${{ secrets.ORACLE_DB_PASSWORD != '' }}"
            
            echo " GitHub Secrets 사용하여 환경변수 설정"

            # 새 컨테이너 실행 (수정된 부분!)
            docker run -d \
              --name hanabank-backend \
              -p 8082:8082 \
              -e SPRING_PROFILES_ACTIVE=production \
              -e ORACLE_DB_URL="$ORACLE_DB_URL" \
              -e ORACLE_DB_USERNAME="$ORACLE_DB_USERNAME" \
              -e ORACLE_DB_PASSWORD="$ORACLE_DB_PASSWORD" \
              -e JAVA_TOOL_OPTIONS="-Dspring.profiles.active=production" \
              ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            
            echo " 컨테이너 내부 환경변수 확인:"
            docker exec hanabank-backend printenv | grep -E "(SPRING_PROFILES_ACTIVE|ORACLE_DB)" || echo "환경변수 확인 실패"
            
            echo "⏳ 애플리케이션 시작 대기 중..."
            for i in {1..5}; do
              if curl -f http://localhost:8082/actuator/health > /dev/null 2>&1; then
                echo " Health Check 성공!"
                break
              fi
              echo " Health Check 시도 $i/5 (15초 대기)..."
              sleep 15
            done
            
            if curl -f http://localhost:8082/actuator/health > /dev/null 2>&1; then
              echo " 배포 성공 - 애플리케이션 정상 작동"
            else
              echo " Health Check 최종 실패 - 컨테이너 로그 확인"
              docker logs hanabank-backend --tail 50
              exit 1
            fi

            echo " HanaBank Backend 배포 완료"
          EOF

          rm private_key.pem

      - name: Deployment status
        if: success()
        run: |
          echo " HanaBank Backend 배포 성공"
          echo "Health Check: http://${{ secrets.EC2_HOST }}:8082/actuator/health"
          echo "API Docs: http://${{ secrets.EC2_HOST }}:8082/swagger-ui.html"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo " HanaBank Backend 배포 실패"
          echo "로그를 확인하여 문제를 해결해주세요."
